#!{{pkgPathFor "core/busybox-static"}}/bin/bash

cd $RAILS_ROOT

{{#if cfg.use_syslog ~}}
export RAILS_LOG_TO_SYSLOG={{cfg.use_syslog}}
{{/if}}


if [ -n "{{cfg.ssl_cert_file}}" ]
then
  SSL_CERT_FILE="{{cfg.ssl_cert_file}}"
fi

exec 2>&1
exec bin/eye load application.eye -f
